### ISSUE TITLE
Sharing within reddit communities

### ISSUE THREAD

**Issue by brh55** [crypti/ccoin#11]
Since this is super convenient for the community, I shall share it to reddit :)

- [x]  /r/webdev
- [x] /r/cryptocurrency

**Comment by brh55** [comment]
![image](https://user-images.githubusercontent.com/6020066/27915563-a007e75a-621b-11e7-857a-f56b22c2ea5d.png)
@radiovisual 💃

**Comment by radiovisual** [comment]
@brh55, nice! We are nearly famous! 🍾  😎
