### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by radiovisual** [crypti/ccoin#2]
version `0.0.1` is currently working, so now it just needs to be published to npm.

**Comment by brh55** [comment]
Going to publish under crypti org so we both have publish access. What is your npm username?

**Comment by radiovisual** [comment]
> What is your npm username?

Same as my github username: **radiovisual**

https://www.npmjs.com/~radiovisual

**Comment by brh55** [comment]
First time using an org, but I have invited you

**Comment by radiovisual** [comment]
awesome. I just tested it, and I was able to publish to npm. So this issue can be closed now. Thanks!

**Comment by brh55** [comment]
@radiovisual can you try publishing with 
`npm publish --access public` ?

**Comment by radiovisual** [comment]
@brh55 , done! I had to bump to `0.0.2` to publish again.

**Comment by brh55** [comment]
@radiovisual Interesting so it appears when it's "org" scoped you need to do 
`npm install @crypti/ccoin`. 
Wondering if it could still be called `ccoin`, but publish to the org?

**Comment by brh55** [comment]
Actually thinking about it, it's probably a good thing as it indicates that the package is from that particular org.

**Comment by radiovisual** [comment]
Hm. there should be a way around that, since when I install things that are part of an org, like AVA (which is avajs/ava) and lodash (which is in lodash/lodash), I only have to do:

```
$ npm install --save ava
$ npm install --save lodash
```

and not:

```
$ npm install --save @avajs/ava
$ npm install --save @lodash/ava
```

but I don't necessarily mind the org prefix, I just don't see it out in the wild very often. I can look into a little later. This is my first time publishing under an org, so I have a little bit to learn on that front.

**Comment by radiovisual** [comment]
its probably just a setting on npm because we transferred ownership of these previously-published and previously-scoped packages

**Comment by brh55** [comment]
Looks like in [@ava](https://www.npmjs.com/org/ava) + [package.json](https://github.com/avajs/ava/blob/master/package.json), they publish as a `ava` and probably transfer it through the npm website, similarly to what I did for eth-price? I'll take a look as well when I'm off work 👍
