### ISSUE TITLE
Allow input to be more than one

### ISSUE THREAD

**Issue by brh55** [crypti/ccoin#6]
@radiovisual  Thoughts on this ability, we would just need to separate the logic used for the `to` string.

**Expected:**
- `ccoin eth,btc btc,doge,eth`
- Skip the one being converted

Would look like such:
```
ETH =>
|- BTC 
|- STRAT
|- DOGE

BTC =>
|- ETH 
|- STRAT
|- DOGE
```

**Comment by radiovisual** [comment]
Yeah, good call. I like that. 👍

**Comment by radiovisual** [comment]
This feature has been added, but it required that I change the API, so I added in two flags `--from` and `--to` (or the aliases `-f` and `-t`).

Also, I can't find a way to support spaces in the cli flags, so I have added in a warning when someone attempts to enter values with spaces:

![image](https://user-images.githubusercontent.com/5614571/27480442-e24625b6-580f-11e7-9149-d7b9bc9ec70b.png)

and then with spaces removed:

![image](https://user-images.githubusercontent.com/5614571/27480459-f0f943fe-580f-11e7-9c43-9b32917bd43b.png)
