### ISSUE TITLE
old `default` profile persists after new default has been created with `--save-default`

### ISSUE THREAD

**Issue by radiovisual** [crypti/ccoin#8]
Proof:

![image](https://user-images.githubusercontent.com/5614571/27535504-070d421c-5a63-11e7-81b8-10f162c2162f.png)

However, you can overwrite the default profile successfully by using the `--save` option:

![image](https://user-images.githubusercontent.com/5614571/27535549-4066bfac-5a63-11e7-9b3b-08805582c45b.png)

**Comment by radiovisual** [comment]
:rofl: OK, I have gone crazy. There is no `--save-default` option, it's `--set-default`. So this is not a bug, it was just me confusing my own API. :rofl:

![image](https://user-images.githubusercontent.com/5614571/27535771-00244f8a-5a64-11e7-93f9-68bee76509a9.png)

**Comment by brh55** [comment]
Hahah 😆!
